### ISSUE TITLE
Conflict with interactive-tools plugin

### ISSUE THREAD

**Issue by ai** [sysgears/pinyarn#1]
`.yarnrc.yml`:

```yaml
nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .pinyarn.js
```

The way to reproduce:

```sh
$ yarn upgrade-interactive
Project/.pinyarn.js:91
  const pluginUrl = config.pluginUrls[plugin];
                                     ^

TypeError: Cannot read property 'interactive-tools' of undefined
    at Object.<anonymous> (Project/.pinyarn.js:91:38)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47
```
